file = open("players.txt", "w")
print("Enter the name of Player 1:")
name1 = input()
print("Enter the name of Player 2:")
name2 = input()
print("Enter the name of Player 3:")
name3 = input()
print("Enter the name of Player 4:")
name4 = input()
file.write(f"{name1}\n{name2}\n{name3}\n{name4}")
file.close()